version: '3.8'

services:
  db_primary:
    build:
      context: .
      dockerfile: ./db_primary/Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    container_name: db_primary
    ports:
      - "5432:5432"
    volumes:
      - db_primary_data:/var/lib/postgresql/data
    networks:
      - db_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  db_network:
    driver: bridge

volumes:
  db_primary_data: